version: '3.2'

services:
  controller:
    build: ./controller
    ports:
      - 8082:8082
    environment:
      MONGO_DB_NAME: $MONGO_MAIN_DATABASE
      MONGO_USER: $MONGO_USERNAME
      MONGO_PASS: $MONGO_PASSWORD
      MONGO_CONTAINER: 'board-database'
    container_name: board-controller
  webapp:
    build: ./webapp
    ports:
      - 80:80
    container_name: board-webapp
  mongodb:
    build: ./mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_MAIN_DATABASE: $MONGO_MAIN_DATABASE
    volumes:
      - type: volume
        source: community-board-db
        target: /data/db
    container_name: board-database
volumes:
  community-board-db:
    external: true
      
